### ISSUE TITLE
为什么  bblive 的延迟比 babylon 严重很多， 没有看到有什么差异，这两个项目；

### ISSUE THREAD

**Issue by vincentqiu** [gqf2008/babylon#1]
bblive :   7s

babylon: 2s 

我本机测试的情况。 

求解

**Comment by gqf2008** [comment]
babylon的并发部分处理的有问题，导致并发上不去，bblive只要满足一个gop就会发送，延迟理论上应该是最小的

**Comment by vincentqiu** [comment]
好吧， 谢谢了
